export class Keys {

    values = {
        192: {value: '`', altValue: '~', style: false},
        49: {value: '1', altValue: '!', style: false},
        50: {value: '2', altValue: '@', style: false},
        51: {value: '3', altValue: '#', style: false},
        52: {value: '4', altValue: '$', style: false},
        53: {value: '5', altValue: '%', style: false},
        54: {value: '6', altValue: '^', style: false},
        55: {value: '7', altValue: '&', style: false},
        56: {value: '8', altValue: '*', style: false},
        57: {value: '9', altValue: '(', style: false},
        48: {value: '0', altValue: ')', style: false},
        189: {value: '-', altValue: '_', style: false},
        187: {value: '=', altValue: '+', style: false},
        8: {value: 'delete', altValue: 'delete', style: false},
        9: {value: 'tab', altValue: 'tab', style: false},
        81: {value: 'q', altValue: 'Q', style: false},
        87: {value: 'w', altValue: 'W', style: false},
        69: {value: 'e', altValue: 'E', style: false},
        82: {value: 'r', altValue: 'R', style: false},
        84: {value: 't', altValue: 'T', style: false},
        89: {value: 'y', altValue: 'Y', style: false},
        85: {value: 'u', altValue: 'U', style: false},
        73: {value: 'i', altValue: 'I', style: false},
        79: {value: 'o', altValue: 'O', style: false},
        80: {value: 'p', altValue: 'P', style: false},
        219: {value: '[', altValue: '{', style: false},
        221: {value: ']', altValue: '}', style: false},
        220: {value: '|', altValue: '|', style: false},
        20: {value: 'caps lock', altValue: 'capsLock', style: false},
        65: {value: 'a', altValue: 'A', style: false},
        83: {value: 's', altValue: 'S', style: false},
        68: {value: 'd', altValue: 'D', style: false},
        70: {value: 'f', altValue: 'F', style: false},
        71: {value: 'g', altValue: 'G', style: false},
        72: {value: 'h', altValue: 'H', style: false},
        74: {value: 'j', altValue: 'J', style: false},
        75: {value: 'k', altValue: 'K', style: false},
        76: {value: 'l', altValue: 'L', style: false},
        186: {value: ';', altValue: ':', style: false},
        222: {value: "'", altValue: '"', style: false},
        13: {value: 'return', altValue: 'return', style: false},
        16: {value: 'shift', altValue: 'shift', style: false},
        90: {value: 'z', altValue: 'Z', style: false},
        88: {value: 'x', altValue: 'X', style: false},
        67: {value: 'c', altValue: 'C', style: false},
        86: {value: 'v', altValue: 'V', style: false},
        66: {value: 'b', altValue: 'B', style: false},
        78: {value: 'n', altValue: 'N', style: false},
        77: {value: 'm', altValue: 'M', style: false},
        188: {value: ',', altValue: '<', style: false},
        190: {value: '.', altValue: '>', style: false},
        191: {value: '/', altValue: '?', style: false},
        32: {value:' ',  altValue: ' ', style: false}
      }

    constructor() {  }
    }

